pipeline {

    agent {
        label 'dev'
    }

    parameters {
        // string defaultValue: 'environment', name: 'DEV'
        choice choices: ['dev', 'prod'], name: 'select_environment'
    }

    environment {
        NAME = "$params.choices"
    }

    stages {

        stage('Prepare SSH') {
            steps {
                sh '''
                    mkdir -p ~/.ssh
                    ssh-keyscan github.com >> ~/.ssh/known_hosts
                    chmod 600 ~/.ssh/known_hosts
                '''
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('build') {
            steps {
                echo "PLATFORM: ==> $NAME" // ${params.DEV}"
                echo "Dev Build Stage"
                script {
                    file = load "script.groovy"
                    file.hello()
                }
            }
            post {
                success {
                    echo "Build Stage Completed!!!"
                }
            }
        }

        stage('test') {
            parallel {
                stage('test_A') {
                    agent {label "$NAME"}
                    steps{
                        echo "Dev Test_A Stage"
                    }
                }
                stage('test_B'){
                    // agent {label 'dev'}
                    agent {label "$NAME"}
                    steps{
                        echo "Dev Test_B Stage"
                    }
                }
            }
            post {
                success {
                    echo "Test Stage Completed!!!"
                }
            }
        }

        stage('deploy') {
            when {
                expression {
                    params.select_environment == 'prod'
                }
                beforeAgent true
            }
            agent {
                label ‘$NAME’
            }
            steps {
                timeout(time:5, unit: 'DAYS'){ input message: 'Do you wish to approved the deployment to Production Server?'}
                echo "$NAME Deploy Stage Begins"
            }
            post {
                success {
                    echo "Deploy Stage Completed!!!"
                }
            }
        }
    }
}