pipeline {
    
    agent any

    stages {
        stage('build') {
            step {
                echo "Dev Build Stage"
            }
        }

        stage('test') {
            step {
                echo "Dev Test Stage"
            }
        }

        stage('deploy') {
            step {
                echo "Dev Deploy Stage"
            }
        }

    }
}