pipeline {

    agent {
        label 'dev'
    }

    parameters {
        // string defaultValue: 'environment', name: 'DEV'
        choice choices: ['dev', 'prod'], name: 'select_environment'
    }

    environment {
        NAME = 'dev'
    }

    stages {

        stage('Prepare SSH') {
            steps {
                sh '''
                    mkdir -p ~/.ssh
                    ssh-keyscan github.com >> ~/.ssh/known_hosts
                    chmod 600 ~/.ssh/known_hosts
                '''
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('build') {
            steps {
                echo "PLATFORM: ==> $NAME ${params.DEV}"
                echo "Dev Build Stage"
            }
            post {
                success {
                    echo "Build Stage Completed!!!"
                }
            }
        }

        stage('test') {
            parallel {
                stage('test_A') {
                    agent {label when {expression {params.select_environment == 'dev'}}}
                    steps{
                        echo "Dev Test_A Stage"
                    }
                }
                stage('test_B'){
                    // agent {label 'dev'}
                    agent {label when {expression {params.select_environment == 'dev'}}}
                    steps{
                        echo "Dev Test_B Stage"
                    }
                }
            }
            post {
                success {
                    echo "Test Stage Completed!!!"
                }
            }
        }

        stage('deploy') {
            steps {
                echo "Dev Deploy Stage"
            }
            post {
                success {
                    echo "Deploy Stage Completed!!!"
                }
            }
        }
    }
}